import type Review from "./Review.model";
import type Shop from "./Shop.model";

interface Products {
  ProductModules: any[];
  ProductName: string;
  Img: string;
  Modules: string | TrustedHTML;
  CommingSoon: boolean;
  Teachers: Teacher[];
  ProductAreas: any;
  CourseCoordinatorUrl?: string;
  ProductImageDetailsUrl?: string;
  ProductEcommerceAttributes?: string;
  CoordinatorName: string;
  MetaDescription: string;
  MetaTitle: string;
  DateUpdated: Date;
  DateInserted: Date;
  CategoryProducts: any;
  ApiEcommerceFrontEndTypes: number;
  Categories?: any;
  StartDate?: any | string;
  EndDate?: any | string;
  UnitsQuantity?: number | any;
  Online?: boolean;
  InStock?: boolean;
  DescriptionFileUrl?: any;
  SKU?: any;
  ProductGroupId?: any;
  Selected?: boolean;
  childrenProducts?: any;
  Children?: any;
  Category: number;
  URLKey?: string;
  ProductId?: number;
  ProductTypeId?: number;
  SmallImageUrl?: string;
  LargeImageUrl?: string;
  Name?: string;
  SpecialPrice?: number;
  Price?: number;
  ShortDescription?: string | null;
  Description?: string;
  description?: string;
  shortDescription?: string;
  slug?: string;
  price?: number;
  title?: string;
  rating?: number;
  discount?: number;
  thumbnail?: string;
  id?: string;
  shop?: Shop;
  brand?: string;
  size?: string[];
  status?: string;
  colors?: string[];
  images?: string[];
  categories?: any[];
  reviews?: Review[];
  published?: boolean;
  VideoTag?: string;
}

export default Products;
